Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Home page
<QuerySet []>
Login page
Login page
Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Programming\BSUIR\MDTWeb\Lab4\HotelSite\views.py", line 25, in login_view
    user = form.get_user()
  File "D:\Programming\BSUIR\MDTWeb\Lab4\HotelSite\forms.py", line 13, in get_user
    user = Client.objects.get(email=email)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 637, in get
    raise self.model.DoesNotExist(
HotelSite.models.Client.DoesNotExist: Client matching query does not exist.
Place page
Starting new HTTPS connection (1): api.ipify.org:443
https://api.ipify.org:443 "GET /?format=json HTTP/1.1" 200 22
User IP: 46.53.252.135 User name: 
Starting new HTTPS connection (1): ipinfo.io:443
https://ipinfo.io:443 "GET /46.53.252.135/geo HTTP/1.1" 200 None
Watching for file changes with StatReloader
D:\Programming\BSUIR\MDTWeb\Lab4\HotelSite\views.py changed, reloading.
Watching for file changes with StatReloader
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Room 2 page
Room 4 page
Login page
Login page
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Statistics page
[['Комната 1', 2252.97], ['Комната 3', 415.0], ['Комната 2', 50.99]]
Internal Server Error: /statistics
Traceback (most recent call last):
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'googlecharts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\Programming\BSUIR\MDTWeb\Lab4\HotelSite\views.py", line 231, in statistics_view
    return render(request, "statistics.html", context)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'googlecharts' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
custom_tags
i18n
l10n
log
static
tz
D:\Programming\BSUIR\MDTWeb\Lab4\Lab4\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Programming\BSUIR\MDTWeb\Lab4\Lab4\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\Programming\BSUIR\MDTWeb\Lab4\Lab4\settings.py changed, reloading.
Watching for file changes with StatReloader
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Statistics page
[['Комната 1', 2252.97], ['Комната 3', 415.0], ['Комната 2', 50.99]]
Internal Server Error: /statistics
Traceback (most recent call last):
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'googlecharts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\Programming\BSUIR\MDTWeb\Lab4\HotelSite\views.py", line 231, in statistics_view
    return render(request, "statistics.html", context)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'googlecharts' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
custom_tags
i18n
l10n
log
static
tz
D:\Programming\BSUIR\MDTWeb\Lab4\Lab4\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Programming\BSUIR\MDTWeb\Lab4\Lab4\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Statistics page
[['Комната 1', 2252.97], ['Комната 3', 415.0], ['Комната 2', 50.99]]
Place page
Starting new HTTPS connection (1): api.ipify.org:443
https://api.ipify.org:443 "GET /?format=json HTTP/1.1" 200 22
User IP: 46.53.252.135 User name: 
Starting new HTTPS connection (1): ipinfo.io:443
https://ipinfo.io:443 "GET /46.53.252.135/geo HTTP/1.1" 200 None
Watching for file changes with StatReloader
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room2_OMi0j1N.jpg
Not Found: /favicon.ico
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room2_OMi0j1N.jpg
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room_nHVkgnL.jpg
Not Found: /media/images/room2_a0ctDsW.jpg
Not Found: /media/images/room_Y21Gqvr.jpg
Not Found: /media/images/room2_OMi0j1N.jpg
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room2_a0ctDsW.jpg
Not Found: /media/images/room_nHVkgnL.jpg
Not Found: /media/images/room2_OMi0j1N.jpg
Not Found: /media/images/room_Y21Gqvr.jpg
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room2_a0ctDsW.jpg
Not Found: /media/images/room_nHVkgnL.jpg
Not Found: /media/images/room2_OMi0j1N.jpg
Not Found: /media/images/room_Y21Gqvr.jpg
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room2_a0ctDsW.jpg
Not Found: /media/images/room_nHVkgnL.jpg
Not Found: /media/images/room2_OMi0j1N.jpg
Not Found: /media/images/room_Y21Gqvr.jpg
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room_nHVkgnL.jpg
Not Found: /media/images/room2_a0ctDsW.jpg
Not Found: /media/images/room2_OMi0j1N.jpg
Not Found: /media/images/room_Y21Gqvr.jpg
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room_nHVkgnL.jpg
Not Found: /media/images/room2_a0ctDsW.jpg
Not Found: /media/images/room2_OMi0j1N.jpg
Not Found: /media/images/room_Y21Gqvr.jpg
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room_nHVkgnL.jpg
Not Found: /media/images/room2_a0ctDsW.jpg
Not Found: /media/images/room2_OMi0j1N.jpg
Not Found: /media/images/room_Y21Gqvr.jpg
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room_nHVkgnL.jpg
Not Found: /media/images/room2_a0ctDsW.jpg
Not Found: /media/images/room_Y21Gqvr.jpg
Not Found: /media/images/room2_OMi0j1N.jpg
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room2_a0ctDsW.jpg
Not Found: /media/images/room_nHVkgnL.jpg
Not Found: /media/images/room_Y21Gqvr.jpg
Not Found: /media/images/room2_OMi0j1N.jpg
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room_nHVkgnL.jpg
Not Found: /media/images/room2_a0ctDsW.jpg
Not Found: /media/images/room_Y21Gqvr.jpg
Not Found: /media/images/room2_OMi0j1N.jpg
Room 3 page
Not Found: /media/images/room_nHVkgnL.jpg
Room 2 page
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room_nHVkgnL.jpg
Not Found: /media/images/room2_a0ctDsW.jpg
Not Found: /media/images/room2_OMi0j1N.jpg
Not Found: /media/images/room_Y21Gqvr.jpg
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room2_a0ctDsW.jpg
Not Found: /media/images/room_nHVkgnL.jpg
Not Found: /media/images/room2_OMi0j1N.jpg
Not Found: /media/images/room_Y21Gqvr.jpg
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room2_a0ctDsW.jpg
Not Found: /media/images/room_nHVkgnL.jpg
Not Found: /media/images/room_Y21Gqvr.jpg
Not Found: /media/images/room2_OMi0j1N.jpg
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /media/images/room_nHVkgnL.jpg
Not Found: /media/images/room2_a0ctDsW.jpg
Not Found: /media/images/room_Y21Gqvr.jpg
Not Found: /media/images/room2_OMi0j1N.jpg
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Watching for file changes with StatReloader
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Statistics page
[['Комната 1', 2252.97], ['Комната 3', 415.0], ['Комната 2', 50.99]]
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Programming\BSUIR\MDTWeb\Lab4\HotelSite\views.py", line 119, in home_view
    return render(request, "home.html",context=context)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 514, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 531, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends "base.html"> must be the first tag in the template.
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet []>
Home page
<QuerySet []>
Home page
<QuerySet []>
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Programming\BSUIR\MDTWeb\Lab4\HotelSite\views.py", line 119, in home_view
    return render(request, "home.html",context=context)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 6: 'static'. Did you forget to register or load this tag?
Home page
<QuerySet []>
Home page
<QuerySet []>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 2>, <Room: Комната 6>, <Room: Комната 7>, <Room: Комната 3>, <Room: Комната 1>, <Room: Комната 4>, <Room: Комната 5>]>
Home page
<QuerySet [<Room: Комната 2>, <Room: Комната 6>, <Room: Комната 7>, <Room: Комната 3>, <Room: Комната 1>, <Room: Комната 4>, <Room: Комната 5>]>
Home page
<QuerySet [<Room: Комната 2>, <Room: Комната 6>, <Room: Комната 7>, <Room: Комната 3>, <Room: Комната 1>, <Room: Комната 4>, <Room: Комната 5>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Room 1 page
Home page
<QuerySet [<Room: Комната 2>, <Room: Комната 6>, <Room: Комната 7>, <Room: Комната 3>, <Room: Комната 1>, <Room: Комната 4>, <Room: Комната 5>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Room 1 page
Booking room 1 page
Room 1 page
Own booking page. Client:   
Place page
Starting new HTTPS connection (1): api.ipify.org:443
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
https://api.ipify.org:443 "GET /?format=json HTTP/1.1" 200 22
User IP: 46.53.252.135 User name: 
Starting new HTTPS connection (1): ipinfo.io:443
https://ipinfo.io:443 "GET /46.53.252.135/geo HTTP/1.1" 200 None
Statistics page
[['Комната 1', 2252.97], ['Комната 3', 415.0], ['Комната 2', 50.99]]
Internal Server Error: /statistics
Traceback (most recent call last):
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\Programming\BSUIR\MDTWeb\Lab4\HotelSite\views.py", line 231, in statistics_view
    return render(request, "statistics.html", context)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 8: 'static'. Did you forget to register or load this tag?
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Login page
Login page
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Own booking page. Client: Олег Олегович Олегович
Login page
Login page
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Room 1 page
Room 1 page
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Statistics page
[['Комната 1', 2252.97], ['Комната 3', 415.0], ['Комната 2', 50.99]]
Internal Server Error: /statistics
Traceback (most recent call last):
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\Programming\BSUIR\MDTWeb\Lab4\HotelSite\views.py", line 231, in statistics_view
    return render(request, "statistics.html", context)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 8: 'static'. Did you forget to register or load this tag?
Statistics page
[['Комната 1', 2252.97], ['Комната 3', 415.0], ['Комната 2', 50.99]]
Internal Server Error: /statistics
Traceback (most recent call last):
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "D:\Programming\BSUIR\MDTWeb\Lab4\HotelSite\views.py", line 231, in statistics_view
    return render(request, "statistics.html", context)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 514, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "C:\Users\vanya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\template\base.py", line 531, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends "base.html"> must be the first tag in the template.
Statistics page
[['Комната 1', 2252.97], ['Комната 3', 415.0], ['Комната 2', 50.99]]
Place page
Starting new HTTPS connection (1): api.ipify.org:443
https://api.ipify.org:443 "GET /?format=json HTTP/1.1" 200 22
User IP: 46.53.252.135 User name: 
Starting new HTTPS connection (1): ipinfo.io:443
https://ipinfo.io:443 "GET /46.53.252.135/geo HTTP/1.1" 200 None
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Not Found: /favicon.png
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Place page
Starting new HTTPS connection (1): api.ipify.org:443
https://api.ipify.org:443 "GET /?format=json HTTP/1.1" 200 22
User IP: 46.53.252.135 User name: 
Starting new HTTPS connection (1): ipinfo.io:443
https://ipinfo.io:443 "GET /46.53.252.135/geo HTTP/1.1" 200 None
Watching for file changes with StatReloader
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Place page
Starting new HTTPS connection (1): api.ipify.org:443
https://api.ipify.org:443 "GET /?format=json HTTP/1.1" 200 22
User IP: 46.53.252.135 User name: 
Starting new HTTPS connection (1): ipinfo.io:443
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
https://ipinfo.io:443 "GET /46.53.252.135/geo HTTP/1.1" 200 None
Place page
Starting new HTTPS connection (1): api.ipify.org:443
https://api.ipify.org:443 "GET /?format=json HTTP/1.1" 200 22
User IP: 46.53.252.135 User name: 
Starting new HTTPS connection (1): ipinfo.io:443
https://ipinfo.io:443 "GET /46.53.252.135/geo HTTP/1.1" 200 None
Place page
Starting new HTTPS connection (1): api.ipify.org:443
https://api.ipify.org:443 "GET /?format=json HTTP/1.1" 200 22
User IP: 46.53.252.135 User name: 
Starting new HTTPS connection (1): ipinfo.io:443
https://ipinfo.io:443 "GET /46.53.252.135/geo HTTP/1.1" 200 None
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Watching for file changes with StatReloader
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
Home page
<QuerySet [<Room: Комната 1>, <Room: Комната 2>, <Room: Комната 3>, <Room: Комната 4>, <Room: Комната 5>, <Room: Комната 6>, <Room: Комната 7>]>
